# Exported from:        http://qe-release-controller1.xebialabs.com:5516/
# Release version:      25.1.0-beta.6
# Date created:         Thu Mar 20 14:42:17 UTC 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_crt.yaml
  - Trigger_time trigger.yaml
  - Variables.yaml
  - Workflow_test workflow 2.yaml
  - Workflow_workflow 1.yaml
