# Exported from:        http://qe-release-controller2.xebialabs.com:5516/
# Release version:      23.3.0-beta.6
# Date created:         Mon Sep 11 08:55:28 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_temp1.yaml
  - Template_temp2.yaml
  - Template_temp3.yaml
  - Template_temp4.yaml
