# Exported from:        http://qe-release-controller1.xebialabs.com:5516/
# Release version:      25.1.0-beta.6
# Date created:         Thu Mar 20 14:42:17 UTC 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: vijay
spec:
- name: time trigger
  type: time.Schedule
  releaseTitle: "${triggerTime}"
  template: crt
  pollType: REPEAT
  periodicity: "60"
  enabled: false
  triggerTime: 2025-03-20T14:39:25.175000
