# Exported from:        http://qe-release-controller1.xebialabs.com:5516/
# Release version:      25.1.0-beta.6
# Date created:         Thu Mar 20 14:42:17 UTC 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: vijay
spec:
- template: test workflow 2
  scheduledStartDate: 2025-03-18T03:30:00Z
  phases:
  - phase: Workflow tasks
    tasks:
    - name: start
      type: xlrelease.Task
    - name: uit
      type: xlrelease.UserInputTask
      description: |-
        Please enter the required information below.


        Just fill some values in this user input task
      variables:
      - null
      - null
      - null
    - name: unix script
      type: remoteScript.Unix
      script: |-
        i=1
        while [ $i -le 20 ]
        do
            echo $i
            i=$(($i+1))
            sleep 1
        done
      address: qe-release-controller1.xebialabs.com
      username: ubuntu
      password: !value "remoteScript_Unix_unix_script_password"
    - name: unix script (copy)
      type: remoteScript.Unix
      script: |-
        i=1
        while [ $i -le 40 ]
        do
            echo $i
            i=$(($i+1))
            sleep 1
        done
      address: qe-release-controller1.xebialabs.com
      username: ubuntu
      password: !value "remoteScript_Unix_unix_script__copy__password"
    - name: unix script (copy) (copy)
      type: remoteScript.Unix
      script: |-
        i=1
        while [ $i -le 60 ]
        do
            echo $i
            i=$(($i+1))
            sleep 1
        done
      address: qe-release-controller1.xebialabs.com
      username: ubuntu
      password: !value "remoteScript_Unix_unix_script__copy___copy__password"
  kind: WORKFLOW
  categories:
  - new one for testing
  - one more so that we can see
  variables:
  - type: xlrelease.StringVariable
    key: var1
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: var1 copy
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: var1 copy copy
    showOnReleaseStart: false
  disableNotifications: true
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_test_workflow_2_scriptUserPassword"
  author: Vijay
  allowTargetFolderOverride: false
  defaultTargetFolder: ./
