# Exported from:        http://LAPTOP-LBQA6LE0:5516/
# Release version:      23.3.0-rc.2
# Date created:         Wed Oct 11 12:15:22 IST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_another copy template check ga 23.3 (2).yaml
  - Template_template check ga 23.3 (1).yaml
  - Template_template check ga 23.3.yaml
