# Exported from:        http://Vijays-MacBook-Pro.local:5516/
# Release version:      25.1.0-1118.113
# Date created:         Tue Nov 19 14:45:46 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_temp01.yaml
