# Exported from:        http://LAPTOP-LBQA6LE0:5516/
# Release version:      23.3.0-rc.2
# Date created:         Wed Oct 11 12:14:29 IST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
