# Exported from:        http://LAPTOP-LBQA6LE0:5516/
# Release version:      23.3.0-rc.2
# Date created:         Wed Oct 11 12:14:29 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: testing
spec:
- template: another copy template check ga 23.3 (2)
  scheduledStartDate: 2023-10-11T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: welcome
      type: xlrelease.Task
    - name: say hello
      type: xlrelease.ScriptTask
      script: print('HELLO !!!! ')
    - name: print numbers
      type: xlrelease.ScriptTask
      script: |-
        for i in range(24):
          print(i)
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_another_copy_template_check_ga_23_3__2__scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
  defaultTargetFolder: ./
- template: template check ga 23.3
  scheduledStartDate: 2023-10-11T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: welcome
      type: xlrelease.Task
    - name: say hello
      type: xlrelease.ScriptTask
      script: print('HELLO !!!! ')
    - name: print numbers
      type: xlrelease.ScriptTask
      script: |-
        for i in range(24):
          print(i)
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_template_check_ga_23_3_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
  defaultTargetFolder: ./
- template: template check ga 23.3 (1)
  scheduledStartDate: 2023-10-11T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: welcome
      type: xlrelease.Task
    - name: say hello
      type: xlrelease.ScriptTask
      script: print('HELLO !!!! ')
    - name: print numbers
      type: xlrelease.ScriptTask
      script: |-
        for i in range(24):
          print(i)
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_template_check_ga_23_3__1__scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
  defaultTargetFolder: ./
