# Exported from:        http://Vijays-MacBook-Pro.local:5516/
# Release version:      25.1.0-225.113
# Date created:         Wed Feb 26 15:03:51 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: test1
spec:
- name: local jenkins server
  type: jenkins.Server
  url: http://localhost:8080
  username: vijay
  password: !value "jenkins_Server_local_jenkins_server_password"
