# Exported from:        http://Vijays-MacBook-Pro.local:5516/
# Release version:      25.1.0-SNAPSHOT
# Date created:         Tue Mar 25 09:17:09 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: test folder
spec:
- name: local jekns1
  type: jenkins.Server
  url: http://localhost:8080
  username: vijay
  password: !value "jenkins_Server_local_jekns1_password"
